# Build LaTeX and upload assets to release

on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Build and release

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env.tex
        env:
          WEBSITE: ${{ secrets.WEBSITE }}
          GENERIC_ADDRESS: ${{ secrets.GENERIC_ADDRESS }}
          BIRTH_DATE: ${{ secrets.BIRTH_DATE }}
          CITIZENSHIP: ${{ secrets.CITIZENSHIP }}
        run: |
          touch env.tex
          echo \\newcommand{\\website}{$WEBSITE} > env.tex
          echo \\newcommand{\\genericaddress}{$GENERIC_ADDRESS} >> env.tex
          echo \\newcommand{\\birthdate}{$BIRTH_DATE} >> env.tex
          echo \\newcommand{\\citizenship}{$CITIZENSHIP} >> env.tex

      - name: Build LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            gtumedei-cv-no-contact-info.tex
            gtumedei-publications.tex

      - name: Update release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cv
          files: |
            gtumedei-cv-no-contact-info.pdf
            gtumedei-publications.pdf
