# Build LaTeX and upload assets to release

on:
  push:
    branches:
      - main

name: Build and release

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add env.tex
        run: touch env.tex

      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: gtumedei-publications.tex

      - name: ls
        run: ls -alh

      - name: Create release asset
        run: echo "Hello, World!" > file.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cv
          files: file.txt
