# Build LaTeX and upload assets to release

on:
  push:
    branches:
      - main

name: Build and release

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add env.tex
        run: |
          touch env.tex
          echo \\newcommand{\\website}{https://www.google.com} > env.tex
          echo \\newcommand{\\genericaddress}{Address} >> env.tex
          echo \\newcommand{\\birthdate}{01/01/1900} >> env.tex
          echo \\newcommand{\\citizenship}{None} >> env.tex

      - name: Build LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            gtumedei-cv-no-contact-info.tex
            gtumedei-publications.tex

      - name: Update release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: cv
          files: |
            gtumedei-cv-no-contact-info.pdf
            gtumedei-publications.pdf
